export const GET_CATALOG = 'GET_CATALOG';
export const SET_CATALOG_FAVOURITES = 'SET_CATALOG_FAVOURITES';
export const SET_CITY = 'SET_CITY'
export const DELL_FAVOURITES = 'DELL_FAVOURITES';
export const SET_NUMBER__PAGES = 'SET_NUMBER__PAGES';
export const SET_MODAL_OPENED = 'SET_MODAL_OPENED';
export const SET_ITEM_MODAL = 'SET_ITEM_MODAL';