export const ResuxActionsType = {
    GET_CATALOG: 'GET_CATALOG',
    SET_CATALOG_FAVOURITES: 'SET_CATALOG_FAVOURITES',
    SET_CITY: 'SET_CITY',
    DELL_FAVOURITES: 'DELL_FAVOURITES',
    SET_NUMBER__PAGES: 'SET_NUMBER__PAGES',
    SET_MODAL_OPENED: 'SET_MODAL_OPENED',
    SET_ITEM_MODAL: 'SET_ITEM_MODAL'
}
